
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ExampleStatus = {
  draft: 'draft',
  active: 'active',
  archived: 'archived'
} as const

export type ExampleStatus = (typeof ExampleStatus)[keyof typeof ExampleStatus]


export const TransactionType = {
  credit: 'credit',
  debit: 'debit'
} as const

export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType]
